branches:
  only:
    - master
    - /^greenkeeper/.*$/

dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - rpm # dist
      - xvfb # testing
      - openjpeg-tools # electron-builder's icon dependency
      - snapd # to, in turn, install snapcraft as a snap

install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then sudo snap install --classic snapcraft && source /etc/profile.d/apps-bin-path.sh && snap list && snapcraft --version; fi
  - npm install

cache: npm

before_script:
  - npm run build

script: # we want to be notified if any of these fail, so use script rather than after_success
  - npm test && npm run dist # only dist if the tests pass
  # coverage is broken, don't waste time re-running the tests
  #- if [[ $TRAVIS_OS_NAME = "linux" ]]; then npm run coveralls; fi
